name: Build Executables

# Auto-build for multiple platforms
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output-name: mysql-sea-sync-linux
            output-path: dist/mysql-sea-sync-linux
          - os: windows-latest
            output-name: mysql-sea-sync-windows.exe
            output-path: dist/mysql-sea-sync-windows.exe
          - os: macos-latest
            output-name: mysql-sea-sync-macos
            output-path: dist/mysql-sea-sync-macos
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --console --name main main.py
        
    - name: Rename executable for release
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          mv dist/main.exe dist/${{ matrix.output-name }}
        else
          mv dist/main dist/${{ matrix.output-name }}
          chmod +x dist/${{ matrix.output-name }}
        fi
      shell: bash
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output-name }}
        path: ${{ matrix.output-path }}
        retention-days: 90
        
    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.output-path }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}